document.addEventListener('DOMContentLoaded',function(){
var s='.modal{display:none;position:fixed;z-index:999999;left:0;top:0;width:100%;height:100%;background:rgba(0,0,0,0.92);backdrop-filter:blur(5px);align-items:center;justify-content:center;overflow-y:auto;padding:20px}.modal-content{position:relative;background:#fff;width:100%;max-width:1000px;display:flex;flex-direction:column;border-radius:12px;overflow:hidden;box-shadow:0 25px 50px -12px rgba(0,0,0,0.5)}@media(min-width:768px){.modal-content{flex-direction:row;height:600px}}.modal-img-container{flex:1.5;background:#f5f5f5;position:relative;overflow:hidden;display:flex;align-items:center;justify-content:center}.modal-img-container img{max-width:90%;max-height:90%;transition:transform 0.3s;cursor:grab}.modal-info{flex:1;padding:40px;display:flex;flex-direction:column;justify-content:center}.modal-info h2{font-family:"Playfair Display",serif;color:#c5a059;margin-bottom:20px}.modal-info p{font-size:1rem;color:#444;line-height:1.6;margin-bottom:30px}.close-modal{position:absolute;top:20px;right:30px;color:#fff;font-size:40px;font-weight:bold;cursor:pointer;z-index:1000000}.zoom-controls{position:absolute;bottom:20px;left:50%;transform:translateX(-50%);display:flex;gap:10px;background:rgba(0,0,0,0.5);padding:5px 15px;border-radius:30px}.zoom-controls button{background:transparent;border:none;color:white;font-size:20px;padding:5px 10px;cursor:pointer}.btn-modal-cta{display:inline-block;padding:14px 36px;background:#c5a059;color:#000;text-decoration:none;text-transform:uppercase;font-size:0.85rem;font-weight:700;text-align:center;border-radius:6px;cursor:pointer;border:none;letter-spacing:1px;font-family:"Montserrat",sans-serif;transition:0.3s}.btn-modal-cta:hover{background:#d4b168}#contact-dialog{display:none;position:fixed;z-index:9999999;left:0;top:0;width:100%;height:100%;background:rgba(0,0,0,0.85);backdrop-filter:blur(8px);align-items:center;justify-content:center}.contact-card{background:#fff;border-radius:16px;padding:40px;max-width:480px;width:90%;text-align:center;position:relative;box-shadow:0 30px 60px rgba(0,0,0,0.4)}.contact-card h3{font-family:"Playfair Display",serif;font-size:1.5rem;color:#c5a059;margin-bottom:8px}.contact-card .contact-person{font-size:0.9rem;color:#333;margin-bottom:5px}.contact-card .contact-phone{font-size:0.85rem;color:#666;margin-bottom:25px}.contact-card .contact-phone a{color:#c5a059;text-decoration:none;font-weight:600}.qr-row{display:flex;justify-content:center;gap:40px;margin-bottom:25px;flex-wrap:wrap}.qr-item{text-align:center}.qr-item img{width:130px;height:130px;border-radius:8px;border:2px solid #eee}.qr-item p{font-size:0.75rem;color:#888;margin-top:8px;font-weight:600}.contact-card .close-dialog{position:absolute;top:15px;right:20px;font-size:28px;cursor:pointer;color:#999}.contact-card .close-dialog:hover{color:#333}';
var st=document.createElement("style");st.innerText=s;document.head.appendChild(st);
var mh='<div id="product-modal" class="modal"><span class="close-modal">&times;</span><div class="modal-content"><div class="modal-img-container"><img id="modal-img" src="" alt="Product"><div class="zoom-controls"><button id="zoom-out">\u2212</button><button id="reset-zoom">\u21BA</button><button id="zoom-in">+</button></div></div><div class="modal-info"><h2 id="modal-title"></h2><p id="modal-desc"></p><button class="btn-modal-cta" id="modal-cta">Inquire Now</button></div></div></div>';
var lang=document.documentElement.lang||'en';
var ctn='';
if(lang==='zh-CN'||lang==='zh'){ctn='<div id="contact-dialog"><div class="contact-card"><span class="close-dialog" onclick="document.getElementById(\'contact-dialog\').style.display=\'none\'">&times;</span><h3>\u8054\u7CFB\u6211\u4EEC</h3><p class="contact-person">\u8054\u7CFB\u4EBA\uFF1A\u56DB\u54E5</p><p class="contact-phone">\u7535\u8BDD\uFF1A<a href="tel:15622220825">15622220825</a></p><div class="qr-row"><div class="qr-item"><img src="/images/wechat-qr.jpg" alt="\u5FAE\u4FE1"><p>\u5FAE\u4FE1\uFF1Atp58886</p></div><div class="qr-item"><img src="/images/whatsapp-qr.jpg" alt="WhatsApp"><p>WhatsApp</p></div></div></div></div>';}
else if(lang==='es'){ctn='<div id="contact-dialog"><div class="contact-card"><span class="close-dialog" onclick="document.getElementById(\'contact-dialog\').style.display=\'none\'">&times;</span><h3>Cont\u00E1ctenos</h3><p class="contact-person">Contacto: Sige</p><p class="contact-phone">Tel: <a href="tel:15622220825">15622220825</a></p><div class="qr-row"><div class="qr-item"><img src="/images/wechat-qr.jpg" alt="WeChat"><p>WeChat: tp58886</p></div><div class="qr-item"><img src="/images/whatsapp-qr.jpg" alt="WhatsApp"><p>WhatsApp</p></div></div></div></div>';}
else{ctn='<div id="contact-dialog"><div class="contact-card"><span class="close-dialog" onclick="document.getElementById(\'contact-dialog\').style.display=\'none\'">&times;</span><h3>Contact Us</h3><p class="contact-person">Contact: Sige</p><p class="contact-phone">Phone: <a href="tel:15622220825">15622220825</a></p><div class="qr-row"><div class="qr-item"><img src="/images/wechat-qr.jpg" alt="WeChat"><p>WeChat: tp58886</p></div><div class="qr-item"><img src="/images/whatsapp-qr.jpg" alt="WhatsApp"><p>WhatsApp</p></div></div></div></div>';}
document.body.insertAdjacentHTML('beforeend',mh);
document.body.insertAdjacentHTML('beforeend',ctn);
var modal=document.getElementById('product-modal'),modalImg=document.getElementById('modal-img'),modalTitle=document.getElementById('modal-title'),modalDesc=document.getElementById('modal-desc'),contactDlg=document.getElementById('contact-dialog'),currentScale=1;
if(lang==='zh-CN'||lang==='zh'){document.getElementById('modal-cta').innerText='\u7ACB\u5373\u54A8\u8BE2';}
else if(lang==='es'){document.getElementById('modal-cta').innerText='Consultar Ahora';}
document.getElementById('modal-cta').onclick=function(e){e.preventDefault();contactDlg.style.display='flex';};
contactDlg.onclick=function(e){if(e.target===contactDlg)contactDlg.style.display='none';};
function openModal(src,title,desc){modalImg.src=src;modalTitle.innerText=title;modalDesc.innerText=desc;modal.style.display='flex';document.body.style.overflow='hidden';currentScale=1;modalImg.style.transform='scale(1)';}
document.addEventListener('click',function(e){var t=e.target.closest('.product-card,.frag-item,.service-item,.cat-card,.cert-item,.opp-card');if(t){e.preventDefault();var img=t.querySelector('img'),title=t.querySelector('h3, h4'),desc=t.querySelector('p');if(img){openModal(img.src,(title||{}).innerText||'',(desc||{}).innerText||'');}}});
document.querySelector('.close-modal').onclick=function(){modal.style.display='none';document.body.style.overflow='auto';};
window.onclick=function(e){if(e.target===modal){modal.style.display='none';document.body.style.overflow='auto';}};
document.getElementById('zoom-in').onclick=function(e){e.stopPropagation();currentScale+=0.2;modalImg.style.transform='scale('+currentScale+')';};
document.getElementById('zoom-out').onclick=function(e){e.stopPropagation();if(currentScale>0.4){currentScale-=0.2;modalImg.style.transform='scale('+currentScale+')';}};
document.getElementById('reset-zoom').onclick=function(e){e.stopPropagation();currentScale=1;modalImg.style.transform='scale(1)';};
document.addEventListener('keydown',function(e){if(e.key==='Escape'){if(contactDlg.style.display==='flex')contactDlg.style.display='none';else if(modal.style.display==='flex'){modal.style.display='none';document.body.style.overflow='auto';}}});
});
